#!/bin/sh

# File:       .xinitrc
# Author:     Julian Orchard <hello@julianorchard.co.uk
# Tag Added:  2022-04-19
# Desciption: An old, but functional, .xinitrc File

# userresources=$HOME/.config/X11/Xresources
# usermodmap=$HOME/.config/X11/Xmodmap
# sysresources=/etc/X11/xinit/Xresources
# sysmodmap=/etc/X11/xinit/.Xmodmap

# Systemctl Fix
#systemctl --user set-environment DISPLAY=:0

# EN-GB Keyboard Layout
setxkbmap -layout gb

# XRDB
xrdb -merge "$HOME"/.config/X11/Xresources

# From Default .xinitrc:
# It just starts programs in xinitrc.d, as I understand it
# if [ -d /etc/X11/xinit/xinitrc.d ]
# then
#   for f in /etc/X11/xinit/xinitrc.d/?*.sh
#   do
#     # If $f executable, execute
#     [ -x "$f" ] && . "$f"
#   done
#   unset f
# fi

# Udiskie
[ -x /usr/bin/udiskie ] && udiskie &

# Execute AwesomeWM
exec awesome
